### ISSUE TITLE
Enhance Documentation for Clarity and User Experience

### ISSUE THREAD

**Issue by ALIPHATICHYD** [EdizKeskin/MangaReader#1]
Hi there! I'm ALIPHATIC, and I'm excited to discover the MangaReader project. I've explored the demo and noticed a few areas where we could enhance the documentation to make it even more informative and user-friendly.

Here are some suggestions:

- Adding a comprehensive Features section:
- Refactoring Installation Steps
- Enhance Built with section:
- Adding Usage section
- Considering additional sections

I'd be happy to contribute to drafting or editing these sections to make the documentation more comprehensive and helpful for both users and developers.

I'm open to any feedback or suggestions on how we can improve the documentation together. Thanks for considering these ideas!

**Comment by EdizKeskin** [comment]
Hello ALIPHATIC

Thank you for your interest in the MangaReader project! I find your suggestions valuable and it's a great idea to improve the documentation on the topics you mentioned, but I haven't written documentation before and to be honest I don't know what to look for. I will try to write a documentation according to your suggestions. If you want to help with this you can open a pull request or contact me.
